name: python

on:
  #schedule:
  #  - cron: "*/20 * * * *"   # هر 20 دقیقه یکبار
  workflow_dispatch:         # اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone https://$TOKEN@github.com/wamir823/data.git bot
          cp -r bot/* ./
          rm -rf bot
          python main.py
